const techSlugMap = {
  "Python": "python",
  "R": "r",
  "Julia": "julia",
  "TensorFlow": "tensorflow",
  "PyTorch": "pytorch",
  "Keras": "keras",
  "Scikit-learn": "scikitlearn",
  "OpenCV": "opencv",
  "NLTK": null, // nggak ada di simple-icons
  "HTML": "html5",
  "CSS": "css3",
  "JavaScript": "javascript",
  "TypeScript": "typescript",
  "PHP": "php",
  "Ruby": "ruby",
  "Go": "go",
  "React.js": "react",
  "Vue.js": "vuejs",
  "Angular": "angular",
  "Laravel": "laravel",
  "Next.js": "nextdotjs",
  "Django": "django",
  "Flask": null,
  "SASS": "sass",
  "C": null,
  "C++": "cplusplus",
  "MicroPython": null,
  "Rust": "rust",
  "NodeMCU": null,
  "PlatformIO": "platformdotio",
  "Arduino": "arduino",
  "ESP-IDF": null,
  "Zephyr": null,
  "Kotlin": "kotlin",
  "Swift": "swift",
  "Objective-C": null,
  "Dart": "dart",
  "Flutter": "flutter",
  "React Native": "react", // pakai react
  "Ionic": "ionic",
  "Xamarin": "xamarin",
  "Jetpack Compose": null,
  "VB.NET": null,
  "C#": "csharp",
  "PowerShell": "powershell",
  "AutoHotkey": null,
  "UiPath Script": null,
  "Blue Prism": null,
  "Automation Anywhere": null,
  "TagUI": null,
  "Robot Framework": null,
};

export default techSlugMap;
